server:
  port: 8080
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/pages
      suffix: .jsp
  data:
    solr:
      host: http://localhost:8083/solr
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
