server:
  port: 80
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://FY-Lee:3306/house
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml